Added implementation
sanek98cv/cinema pull request #1
Opened 2021-01-26 14:40 UTC by sanek98cv

2021-01-26 15:23 UTC, engineer027 approved these changes

2021-01-27 08:11 UTC, Sofasmile requested changes

2021-01-27 08:11 UTC, Sofasmile commented on src/main/java/com/dev/cinema/dao/impl/MovieDaoImpl.java
> +            throw new SessionException("Can't insert Movie entity", e);
```suggestion
            throw new DataProcessingException("Can't insert Movie entity " + movie, e);
```

2021-01-27 08:11 UTC, Sofasmile commented on src/main/java/com/dev/cinema/dao/impl/MovieDaoImpl.java
> +    public Movie add(Movie movie) throws SessionException {
```suggestion
    public Movie add(Movie movie) {
```

2021-01-27 08:11 UTC, Sofasmile commented on src/main/java/com/dev/cinema/exception/SessionException.java
> +        super(message);
```suggestion
        super(message, e);
```

2021-01-27 10:36 UTC, RomanDubovskyi requested changes

2021-01-27 10:36 UTC, RomanDubovskyi commented on src/main/java/com/dev/cinema/dao/impl/MovieDaoImpl.java
> +        } catch (DataProcessingException e) {
wrote in channel about it

2021-01-27 10:42 UTC, sanek98cv commented on src/main/java/com/dev/cinema/dao/impl/MovieDaoImpl.java
> +        } catch (DataProcessingException e) {
done

2021-01-27 11:13 UTC, RomanDubovskyi approved these changes

2021-01-28 08:20 UTC, merged