Added implementation
sanek98cv/cinema pull request #3
Opened 2021-02-02 16:30 UTC by oleksandrdziubiuk

2021-02-02 17:17 UTC, engineer027 approved these changes

2021-02-03 07:42 UTC, KseniiaMakarova requested changes

2021-02-03 07:42 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/Main.java
> +        user.setPassword("123");
there is no need to do this here - User is created in and returned from `register()` method

2021-02-03 07:42 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/security/AuthenticationService.java
> +    User registration(String email, String password);
```suggestion
    User register(String email, String password);
```

2021-02-03 07:42 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/util/HashUtil.java
> +
redundant empty line

2021-02-03 09:30 UTC, KseniiaMakarova approved these changes

2021-02-03 09:32 UTC, merged